# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f05ae233d659e96cb4956ae023fe060e04cbe8bb5e51094d28310ad43b9925cde1f995e1554fcd543b604be8e9c7ec7655532c81d086a70f2653862151be1b2b

test:
  secret_key_base: 63135db8c79f65fdbe0ccc3a169603217b6bb51b2904f18bd9bed67b543deb79f418ef4a32cbe89646f285626bca844e60668c0bf3dbc21fbe9afbc0c555b7d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
